### ISSUE TITLE
Everything 

### ISSUE THREAD

**Issue by Itsamejonah** [AyeItsHarry/WiiLinkPatcherAndroid#1]
Everything is just bad. No APK, just instructions. I hate this.

**Comment by AyeItsHarry** [comment]
If you hate it, don't use it

**Comment by LNLenost** [comment]
Couldn't agree more with Harry. How can you even expect an APK from a port
of a Linux script? You need termux to run the script. If you think an APK
solves all your problem, then stay away from modding in general. Or at
least try and learn how this works. The work this guy made is great.
